### ISSUE TITLE
introducing json config files

### ISSUE THREAD

**Issue by paolap** [ACCESS-Hive/APP4#3]
Introducing json (?) configuration files to pass simulation parameters like path, experiment, start and end year etc. Currently these are set in the a bash script as environment variables and then re-read one by one in python using os.eviron.get().

If anyone else prefer a different format let me know, but I think it should be easier anyway to change format once we ahem a list of all the "settings"

**Comment by aidanheerdegen** [comment]
I'd definitely vote for yaml, which is a JSON subset but designed to be more friendly to edit.

**Comment by paolap** [comment]
We haven't got to that bit yet, so definitely we can do yaml, the important part is to have everything in the one config file rather than across bash codes.

**Comment by paolap** [comment]
We started doing this, using yaml, the main file is custom_app.yaml
we'll probably should find a better name!
This currently has two dictionaries
cmor - contains all the paths, NCI details (projects, ncpus etc.), tables and var to process,  drs and filename schemas ...

attrs - has the global attributes to add to the final files with some indications via comments of what has to be added to follow CMIP6 and/or ACDD conventions or potentially other conventions

**Comment by paolap** [comment]
We're also in the process of moving out of the code and into similarly defined dictionaries a lot of other settings: land types, realms, basin types, pressure levels etc.

**Comment by paolap** [comment]
Most of this is done we'll open new issues in new repo if necessary
